# status bar position
set -g status-position top #bottom
set -g status-justify absolute-centre

# terminal colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g allow-passthrough on

set -g set-titles on
set -g set-titles-string "#S" #"#S - #W"

set -g mouse on
set -g base-index 1
set -g pane-base-index 1

# colors
set -g status-style bg=default
set -g window-status-style fg="#ffffff"
set -g window-status-current-style bg="#e6db74",fg="#000000"
# c-b w menu highlight 
set -g mode-style bg="#e6db74",fg="#000000"
# command line colors
set -g message-style bg=default,fg="#ffffff"
set -g message-command-style bg=default,fg="#ffffff"
# pane borders
set -g pane-border-style fg=colour238
set -g pane-active-border-style fg=colour250

# formats
set -g window-status-format " #I:#W "
set -g window-status-current-format " #[bold]#I:#W "

set -g status-left "" #"[#S]"
set -g status-right "" #"#h %H:%M"

bind h previous-window
bind l next-window

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
