# status bar position
set -g status-position bottom

# colors
set -g status-style bg=default
set -g status-fg "#ffffff"

set -g window-status-style fg="#ffffff"
set -g window-status-current-style fg=color2

# formats
set -g window-status-format " #I:#W "
set -g window-status-current-format " #[bold]#I:#W "

set -g status-right "#h %H:%M"

